### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by arthurits** [arthurits/RadialGaugePlot#1]
# This project is participating in Hacktoberfest 2021! #

Hacktoberfest is an event that encourages contributions to open-source projects run by Digital Ocean. Participants who contribute to 4 merged pull requests may be eligible for a free T-shirt.

- **PR Quality Standards:** https://hacktoberfest.digitalocean.com/resources/qualitystandards
- **Information for Participants:** https://hacktoberfest.digitalocean.com/resources/participation
- **Maintainers:** https://hacktoberfest.digitalocean.com/resources/maintainers

# Recommended projects to tackle #

- Abstract the plot title into an object with a `Render` method and properties (Font, etc.)
- Improve the `ComputeRects()` function, making space for plot title and possible axis.
- Improve the control's properties names.

**Comment by ashwin003** [comment]
Is this available? What are the expectations?
